services:
  - type: web
    name: eduinfonew-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: railway-db
          property: connectionString

databases:
  - name: railway-db
