# Generated by Django 5.2.1 on 2025-05-30 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='activites/')),
                ('classes_cibles', models.CharField(default='all', max_length=500)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نشاط',
                'verbose_name_plural': 'الأنشطة',
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='العنوان')),
                ('enonce', models.TextField(verbose_name='نص التمرين')),
                ('classes_cibles', models.CharField(default='all', max_length=500)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تمرين',
                'verbose_name_plural': 'التمارين',
            },
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='العنوان')),
                ('fichier', models.FileField(upload_to='fichiers/', verbose_name='الملف')),
                ('classes_cibles', models.CharField(default='all', max_length=500, verbose_name='الأقسام المستهدفة')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ملف',
                'verbose_name_plural': 'الملفات',
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='الاسم')),
                ('prenom', models.CharField(max_length=100, verbose_name='اللقب')),
                ('classe', models.CharField(choices=[('1am1', '1AM1'), ('1am2', '1AM2'), ('1am3', '1AM3'), ('1am4', '1AM4'), ('1am5', '1AM5'), ('2am1', '2AM1'), ('2am2', '2AM2'), ('2am3', '2AM3'), ('2am4', '2AM4'), ('2am5', '2AM5'), ('3am1', '3AM1'), ('3am2', '3AM2'), ('3am3', '3AM3'), ('3am4', '3AM4'), ('3am5', '3AM5'), ('4am1', '4AM1'), ('4am2', '4AM2'), ('4am3', '4AM3'), ('4am4', '4AM4'), ('4am5', '4AM5')], max_length=10, verbose_name='القسم')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تلميذ',
                'verbose_name_plural': 'التلاميذ',
                'unique_together': {('nom', 'prenom', 'classe')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='المحتوى')),
                ('expediteur', models.CharField(choices=[('eleve', 'تلميذ'), ('enseignant', 'أستاذ')], max_length=20)),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eleve')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='العلامة')),
                ('commentaire', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eleve')),
            ],
            options={
                'verbose_name': 'علامة',
                'verbose_name_plural': 'العلامات',
            },
        ),
        migrations.CreateModel(
            name='CompletionActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completee', models.BooleanField(default=False)),
                ('date_completion', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.activite')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eleve')),
            ],
            options={
                'unique_together': {('eleve', 'activite')},
            },
        ),
        migrations.CreateModel(
            name='ReponseExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField(verbose_name='الإجابة')),
                ('corrigee', models.BooleanField(default=False)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eleve')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercice')),
            ],
            options={
                'unique_together': {('eleve', 'exercice')},
            },
        ),
    ]
