# Generated by Django 5.2.1 on 2025-06-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Message de notification')),
                ('lu', models.BooleanField(default=False, verbose_name='Lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type_notification', models.CharField(choices=[('new_file', 'Nouveau Fichier'), ('new_activity', 'Nouvelle Activité'), ('new_exercise', 'Nouvel Exercice'), ('grade_updated', 'Note Mise à Jour'), ('new_message', 'Nouveau Message'), ('activity_reminder', "Rappel d'Activité")], default='new_file', max_length=50, verbose_name='Type')),
                ('lien_relatif', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lien relatif (frontend)')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.eleve')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
